language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer jekyll-coffeescript jekyll-paginate

script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
